added time and search -check

diff --git a/.github/workflows/check-links.yml b/.github/workflows/check-links.yml
--- a/.github/workflows/check-links.yml
+++ b/.github/workflows/check-links.yml
@@ -52,6 +52,14 @@ jobs:
           git add README.md
           git diff --quiet && git diff --staged --quiet || (git commit -m "Update README counter [skip ci]" && git push)
 
+      - name: Setup Dart
+        if: steps.check_commit.outputs.CHECK_LINKS == 'true'
+        uses: dart-lang/setup-dart@v1
+
+      - name: Install linkcheck
+        if: steps.check_commit.outputs.CHECK_LINKS == 'true'
+        run: dart pub global activate linkcheck
+
       - name: Extract and clean URLs from README
         if: steps.check_commit.outputs.CHECK_LINKS == 'true'
         run: |
@@ -64,7 +72,7 @@ jobs:
           while IFS= read -r url
           do
             echo "Checking: $url"
-            timeout 30s filiph/linkcheck@2.0.23 "$url" -e > "linkcheck_results/$(echo $url | md5sum | cut -d' ' -f1).txt" 2>&1 || echo "Error or timeout occurred for $url"
+            timeout 30s linkcheck "$url" -e > "linkcheck_results/$(echo $url | md5sum | cut -d' ' -f1).txt" 2>&1 || echo "Error or timeout occurred for $url"
           done < urls.txt
 
       - name: Compile linkcheck results
